### ISSUE TITLE
Found wrong typing 'lacture'

### ISSUE THREAD

**Issue by yerin1198** [jwmsg0525/KlasPlugin#3]
![image](https://user-images.githubusercontent.com/72977199/99105212-76942d80-2625-11eb-82ab-3769e599bb2e.png)
I found wrong typing 'lacture'. Please correct the word to 'lecture'.

**Comment by jwmsg0525** [comment]
Thanks for creating the issue.  The issue is a typo in the commit message.  Commit messages must be spelled correctly, but often due to developer mistakes or errors, there can be spelling problems.  We sincerely thank you for your continued interest, and in the future, we will familiarize ourselves with and use the correct message for committing.
